# Configuración del analizador estático de Dart/Flutter
# Aplica las reglas recomendadas y excluye carpetas innecesarias.

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Aquí puedes agregar o quitar reglas específicas si lo deseas.
    # Ejemplos:
    # avoid_print: false
    # prefer_single_quotes: true

analyzer:
  exclude:
    - flutter/**      # Ignora archivos ajenos al proyecto que puedan causar errores
    - test_driver/**  # (Opcional) Ignora pruebas de integración si no usas integration_test
